// Trains the production model on the real CGWB Pune well dataset and
// emits src/lib/ml/pretrainedReal.ts (the model shipped with the app).
//
// Run:  npx tsc scripts/train-real.ts --outDir <tmp> --module commonjs \
//         --target es2020 --moduleResolution node --esModuleInterop --skipLibCheck
//       node <tmp>/scripts/train-real.js > src/lib/ml/pretrainedReal.ts

import { realTrainingExamples, REAL_FEATURE_NAMES } from '../src/lib/ml/realFeatures'
import { trainLogReg } from '../src/lib/ml/logreg'

const data = realTrainingExamples()
const pos = data.filter((d) => d.y === 1).length
console.error(`training examples: ${data.length} (${pos} success / ${data.length - pos} poor-dry)`)

const { model, history } = trainLogReg(
  data.map(({ x, y }) => ({ x, y })),
  {
    datasetTag: `CGWB Pune exploration wells (n=${data.length}, NAQUIM Annexure-I)`,
    featureNames: [...REAL_FEATURE_NAMES],
    seed: 11,
    epochs: 800,
    learningRate: 0.35,
    l2: 0.03,
    valFraction: 0.25,
  },
)

const m = model.valMetrics
console.error(
  `val (n=${m.n}): acc ${(m.accuracy * 100).toFixed(1)}% · AUC ${m.auc.toFixed(3)} · ` +
    `P ${(m.precision * 100).toFixed(0)}% R ${(m.recall * 100).toFixed(0)}% F1 ${m.f1.toFixed(2)}`,
)
console.error(`confusion: TP ${m.cm.tp} FP ${m.cm.fp} TN ${m.cm.tn} FN ${m.cm.fn}`)
console.error(`loss ${history[0].trainLoss.toFixed(3)} -> ${history[history.length - 1].trainLoss.toFixed(3)}`)

// weight report for eyeballing
model.featureNames.forEach((n, i) => console.error(`  w ${n}: ${model.weights[i].toFixed(3)}`))

const banner = `// AUTO-GENERATED by scripts/train-real.ts — do not edit by hand.
// Production model trained on the real CGWB Pune exploration-well dataset
// (NAQUIM Annexure-I; ${data.length} pump-tested wells). Validation:
// accuracy ${(m.accuracy * 100).toFixed(1)}%, AUC ${m.auc.toFixed(3)}, F1 ${m.f1.toFixed(2)} on ${m.n} held-out wells.

import type { TrainedModel } from './logreg'

export const PRETRAINED_REAL: TrainedModel = `

console.log(banner + JSON.stringify(model, null, 2) + '\n')
