// AUTO-GENERATED by scripts/train-real.ts — do not edit by hand.
// Production model trained on the real CGWB Pune exploration-well dataset
// (NAQUIM Annexure-I; 101 pump-tested wells). Validation:
// accuracy 80.0%, AUC 0.921, F1 0.88 on 25 held-out wells.

import type { TrainedModel } from './logreg'

export const PRETRAINED_REAL: TrainedModel = {
  "version": 1,
  "featureNames": [
    "Taluka rainfall (log mm/yr)",
    "GW development stage (%)",
    "Taluka yield potential (0–3)",
    "Drought-prone taluka",
    "Pre-monsoon water level (m bgl)",
    "Aquifer-I bottom depth (m)",
    "Aquifer-II zone depth (m)",
    "Aquifer-II zone thickness (m)",
    "Seasonal WL recovery (m)"
  ],
  "weights": [
    -0.1057706140479694,
    0.12686865147423157,
    -0.0689786357729827,
    -0.13515452744757755,
    -0.8045661929653467,
    0.037088914253486545,
    -0.061209278930698476,
    1.1306365859939682,
    -0.21970754322222677
  ],
  "bias": 0.7473490848440191,
  "means": [
    6.727976464350044,
    66.63210526315788,
    2.1578947368421053,
    0.5526315789473685,
    33.014736842105265,
    19,
    110.25,
    3.861842105263158,
    14.358657894736842
  ],
  "stds": [
    0.5068637664581582,
    28.650149779887233,
    1.0072452215265597,
    0.4972222007287151,
    33.44872247869959,
    5.71931169947831,
    42.529594958903864,
    3.4033639359216945,
    13.415674981108982
  ],
  "datasetTag": "CGWB Pune exploration wells (n=101, NAQUIM Annexure-I)",
  "trainedAt": "2026-07-06T18:55:40.893Z",
  "nTrain": 76,
  "nVal": 25,
  "epochs": 800,
  "valMetrics": {
    "n": 25,
    "accuracy": 0.8,
    "auc": 0.9206349206349206,
    "precision": 0.782608695652174,
    "recall": 1,
    "f1": 0.878048780487805,
    "cm": {
      "tp": 18,
      "fp": 5,
      "tn": 2,
      "fn": 0
    },
    "calibration": [
      {
        "mid": 0.1,
        "predicted": 0.08331526179958608,
        "observed": 0,
        "count": 1
      },
      {
        "mid": 0.30000000000000004,
        "predicted": 0.30000000000000004,
        "observed": -1,
        "count": 0
      },
      {
        "mid": 0.5,
        "predicted": 0.525949528238289,
        "observed": 0.2,
        "count": 5
      },
      {
        "mid": 0.7,
        "predicted": 0.7374963229412153,
        "observed": 0.8333333333333334,
        "count": 12
      },
      {
        "mid": 0.9,
        "predicted": 0.8927589328332232,
        "observed": 1,
        "count": 7
      }
    ]
  }
}

